# following instructions from https://goreleaser.com/ci/actions/#usage
name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # this 'fetch-depth: 0' is required by goreleaser
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.ZZ_TOKEN }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
